apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: ajaygk/nginxapp:${BUILD_TIMESTAMP}
      ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: nodeapp
spec:
  selector:
    app: nodeapp
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
